ALTER TABLE categories
ALTER COLUMN color TYPE VARCHAR(100);

UPDATE categories
SET color = (SELECT a
             FROM (VALUES ('bg-red-300'),
                          ('bg-red-400'),
                          ('bg-red-500'),
                          ('bg-red-600'),
                          ('bg-red-700'),
                          ('bg-orange-300'),
                          ('bg-orange-400'),
                          ('bg-orange-500'),
                          ('bg-orange-600'),
                          ('bg-orange-700'),
                          ('bg-amber-300'),
                          ('bg-amber-400'),
                          ('bg-amber-500'),
                          ('bg-amber-600'),
                          ('bg-amber-700'),
                          ('bg-yellow-300'),
                          ('bg-yellow-400'),
                          ('bg-yellow-500'),
                          ('bg-yellow-600'),
                          ('bg-yellow-700'),
                          ('bg-lime-300'),
                          ('bg-lime-400'),
                          ('bg-lime-500'),
                          ('bg-lime-600'),
                          ('bg-lime-700'),
                          ('bg-green-300'),
                          ('bg-green-400'),
                          ('bg-green-500'),
                          ('bg-green-600'),
                          ('bg-green-700'),
                          ('bg-emerald-300'),
                          ('bg-emerald-400'),
                          ('bg-emerald-500'),
                          ('bg-emerald-600'),
                          ('bg-emerald-700'),
                          ('bg-teal-300'),
                          ('bg-teal-400'),
                          ('bg-teal-500'),
                          ('bg-teal-600'),
                          ('bg-teal-700'),
                          ('bg-cyan-300'),
                          ('bg-cyan-400'),
                          ('bg-cyan-500'),
                          ('bg-cyan-600'),
                          ('bg-cyan-700'),
                          ('bg-sky-300'),
                          ('bg-sky-400'),
                          ('bg-sky-500'),
                          ('bg-sky-600'),
                          ('bg-sky-700')) v(a)
             WHERE categories.color <> v.a
             ORDER BY RANDOM()
             LIMIT 1);